wakatime/browser-wakatime

assets/js/options.js, gulpfile.js, manifest.json, public/js/options.js
Updated manifest to exclude chrome styles and added animation to option alert.
=> Added animation to options alert and removed chrome styles

README.md, package.json
It just simplifies it a bit. One command to build and have ready for Chrome to import.
=> Consolidate initial dev commands with `npm start`

assets/js/core/WakaTimeCore.js, assets/less/bootstrap/bootstrap.less, assets/less/bootstrap/button-groups.less, assets/less/bootstrap/forms.less, assets/less/bootstrap/input-groups.less, assets/less/bootstrap/mixins/tab-focus.less, assets/less/bootstrap/panels.less, assets/less/bootstrap/scaffolding.less, assets/less/bootstrap/theme.less, assets/less/bootstrap/variables.less
=> use null instead of false in data that could be sent to api

devtools.html, gulpfile.js, options.html, package-lock.json, package.json, popup.html
The polyfill wasn't loaded before all scripts resulting in error messages in chrome.
Also simplify copying of polyfill, this change though requires node 8 or newer but this should be fine as node is only necessary to build the extension
=> Update polyfill and load in all locations

assets/js/core/WakaTimeCore.js, assets/js/events.js
=> support multiple browser windows

assets/js/core/WakaTimeCore.js
This PR will add features below and closes #93
- ignore trailing `/` or `@@`
- ignore the `http://` or `https://` prefixes on whitelisted URLs
- ignore case sensitivity in URL
=> Fix whitelist matching issues

.bowerrc, bower.json, gulpfile.js, package-lock.json, package.json, xclap.ts
=> remove bower dependancy and covert packages to npm

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adding github templates
- @alanhamlett
=> add some github template files

gulpfile.js, package-lock.json, package.json, xclap.ts
removed most gulp tasks
Manually check extension still works after build
- @alanhamlett
=> removed most gulp tasks

package-lock.json, package.json
Remove unused dep, since bower was removed
- @alanhamlett
=> remove bower

.github/workflows/nodejs.yml
Add CI for next branch, to allow for breaking changes
- @alanhamlett
=> add next branch for ci

.github/workflows/nodejs.yml
The migration to a fully webpack build
- @alanhamlett
=> [WIP] add next branch for ci (#121)

package-lock.json, package.json, setupTests.ts, src/components/MainList.test.tsx, src/components/MainList.tsx, src/components/NavBar.tsx, src/components/WakaTime.tsx, src/core/WakaTimeCore.ts, src/popup.tsx, src/utils/changeExtensionIcon.ts, src/utils/changeExtensionTooltip.ts
* Enable/disable logging
* use redux for enable disable logging
* Update deprecated dependency and test for `webextension-polyfill` extension with jest and sinon
=> chore: enable disable logging

assets/js/components/Options.jsx, src/components/Options.tsx, src/components/SitesList.tsx, src/options.tsx
* Implements options TS component 
* Stores and loads in browser storage user settings
=> chore: implement options component

assets/less/app.less, src/components/NavBar.tsx, src/components/Options.tsx, src/components/WakaTime.tsx, src/utils/user.ts
Move `API Key` input to options view
https://user-images.githubusercontent.com/1050904/213265074-cb1b49e8-5899-483b-987b-17c424cd86f8.mp4
=> chore: move api key input to options view

src/background.ts, src/components/MainList.test.tsx, src/config/config.test.ts, src/config/config.ts
* Service worker listener events that send heartbeats to Wakatime backend api
=> implement service worker events

src/components/Alert.tsx, src/components/WakaTime.tsx, src/manifests/chrome.json, src/manifests/firefox.json
* Bumps the version of the extension
* Displays a message in the extension when users dont have their api key set up
https://user-images.githubusercontent.com/1050904/219065709-7e689a54-173c-4c6c-b7ad-65f7286c5c02.mp4
=> Sebas prompt for api key

src/core/WakaTimeCore.ts, src/manifests/chrome.json, src/types/user.ts, src/utils/checkCurrentUser.ts, src/utils/user.ts
Validates if a users does not have a `apiKey` set and its logged into wakatime in the browser than it sets the apiKey of the current user logged into wakatime
https://user-images.githubusercontent.com/1050904/219106578-a655877e-178a-474a-be02-902a99d0d4ff.mp4
=> chore: get api key from coookie

src/manifests/chrome.json, src/manifests/firefox.json, src/utils/changeExtensionState.ts
* Bumps minor version to 3.0.4
* fixes bug with browser polyfill when sending heartbeats (happens on change icon color)
=> chore: fixes bug with browser polyfill when sending heartbeats

src/components/Options.tsx, src/core/WakaTimeCore.ts, src/manifests/chrome.json, src/manifests/firefox.json
https://github.com/orgs/wakatime/projects/4/views/1?layout=board&pane=issue&itemId=17764419
Support for whitelist wildcards in URLs
=> fix: log whitelist wildcards

src/manifests/chrome.json, src/manifests/firefox.json, src/wakatimeScript.ts
- [ *] I have run `npm test` locally and there are no warnings or errors, from lint or test
- [ *] I have added screenshots if applicable
Support for Figma
CSS selector for Figma:
Extension setup:
https://github.com/wakatime/chrome-wakatime/issues/181
* built and installed locally
* "https://www.figma.com/" added to white list
* open random project at Figma
* discover "projectDetails" variable at runtime
* ![Screenshot from 2023-03-30 01-39-45](https://user-images.githubusercontent.com/17720557/228674266-ce746488-5e5d-4eb2-ae79-0ea03c69c59d.png)
- @alanhamlett
=> ISSUE-181: Support for Figma. Refactor Canva support.

src/core/WakaTimeCore.ts
=> Add operating system to user agent string

src/background.ts
Keep SW alive
https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension
=> Keep SW alive

src/manifests/chrome.json, src/manifests/firefox.json
=> bump to version 3.0.14

src/manifests/firefox.json
=> Description in manifest should match browser

src/manifests/chrome.json, src/manifests/firefox.json
=> Bump version to 3.0.18

src/manifests/chrome.json, src/manifests/edge.json, src/manifests/firefox.json
=> Bump version to v3.0.20

src/manifests/chrome.json, src/manifests/edge.json, src/manifests/firefox.json
=> bump version to 3.0.21

src/manifests/chrome.json, src/manifests/edge.json, src/manifests/firefox.json
**Bump to v3.0.22**
Updates bootstrap to v5
=> bump to v3.0.22

src/core/WakaTimeCore.ts
=> fix: return entire url when loggingType is `entire url` issue #235

src/components/Options.tsx
=> Close options window on save #202

src/core/WakaTimeCore.ts
=> Always initialize local heartbeats db

README.md
Now that the app is also available on Firefox and Edge, it feels appropriate to update the references to Chrome on README.md.
=> Replaced Chrome references
